cloud:
  aws:
    credentials:
      access-key: AKIASXS53XQRYGEG4RPT
      secret-key: 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
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: practice-demo-bucket-23


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

